# Generated by Django 5.1.6 on 2025-03-02 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='descricao',
            new_name='solicitacao',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='usuario',
        ),
        migrations.AddField(
            model_name='lead',
            name='cliente_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='criador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leads_criador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='finalidade',
            field=models.IntegerField(choices=[(0, 'Consumo'), (1, 'Revenda')], default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='origem',
            field=models.IntegerField(choices=[(0, 'Outros'), (1, 'WhatsApp'), (2, 'Telegram'), (3, 'Facebook'), (4, 'Instagram'), (5, 'LinkedIn'), (6, 'Email'), (7, 'Telefone'), (8, 'Site Icetar')], default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='responsavel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leads_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='temperatura',
            field=models.IntegerField(choices=[(0, 'Baixa'), (1, 'Normal'), (2, 'Alta')], default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='ticket',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Serviço'), (1, 'Produto'), (2, 'Peça')], default=0),
        ),
    ]
