# Generated by Django 5.1.6 on 2025-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0004_leadacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='orcamento_omie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadacao',
            name='acao',
            field=models.CharField(choices=[(0, 'Criação'), (1, 'Comentarios'), (2, 'Alteração de Status'), (3, 'Solicitação de Cliente'), (4, 'Informação de Analise'), (5, 'Troca de Responsável')], max_length=20),
        ),
    ]
