# Generated by Django 5.1.6 on 2025-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0005_lead_forma_pagamento_lead_orcamento_omie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.BigIntegerField(unique=True)),
                ('codigo_produto_integracao', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(max_length=500)),
                ('unidade', models.CharField(blank=True, max_length=10, null=True)),
                ('ncm', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_familia', models.BigIntegerField(blank=True, null=True)),
                ('tipo_item', models.CharField(blank=True, max_length=5, null=True)),
                ('peso_liq', models.FloatField(default=0)),
                ('peso_bruto', models.FloatField(default=0)),
                ('altura', models.FloatField(default=0)),
                ('largura', models.FloatField(default=0)),
                ('profundidade', models.FloatField(default=0)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('dias_garantia', models.IntegerField(default=0)),
                ('dias_crossdocking', models.IntegerField(default=0)),
                ('descricao_detalhada', models.TextField(blank=True, null=True)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
