# Generated by Django 5.1.6 on 2025-03-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0007_caracteristica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='conteudo',
            field=models.CharField(max_length=255),
        ),
    ]
