# Generated by Django 5.1.6 on 2025-03-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0008_alter_caracteristica_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='fluxo.lead')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='fluxo.produto')),
            ],
            options={
                'unique_together': {('lead', 'produto')},
            },
        ),
    ]
