# Generated by Django 5.1.6 on 2025-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0010_produto_custo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
