# Generated by Django 5.1.6 on 2025-03-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0013_lead_analisado_em_lead_apc_em_lead_apv_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status_apc',
            field=models.IntegerField(choices=[(0, 'Não Cotado'), (1, 'Aguardando Retorno')], default=0),
        ),
    ]
