# Generated by Django 5.1.6 on 2025-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0014_lead_status_apc'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='prazo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.IntegerField(default=0),
        ),
    ]
