# Generated by Django 5.1.6 on 2025-03-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0015_produto_data_validade_produto_prazo_produto_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadproduto',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadproduto',
            name='prazo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadproduto',
            name='validade',
            field=models.IntegerField(default=0),
        ),
    ]
