# Generated by Django 5.1.6 on 2025-03-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0016_leadproduto_custo_unitario_leadproduto_prazo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadproduto',
            old_name='valor',
            new_name='valor_unitario',
        ),
    ]
