# Generated by Django 5.1.6 on 2025-03-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0017_rename_valor_leadproduto_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadacao',
            name='acao',
            field=models.CharField(choices=[(0, 'Criação'), (1, 'Comentarios'), (2, 'Alteração de Status'), (3, 'Solicitação de Cliente'), (4, 'Informação de Analise'), (5, 'Troca de Responsável'), (6, 'Informação para o comprador'), (7, 'Produto adicionado ao lead'), (8, 'Produto removido do lead'), (9, 'Produto editado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
