# Generated by Django 5.1.6 on 2025-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0019_alter_produto_custo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadacao',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='leads_arquivos/'),
        ),
        migrations.AddField(
            model_name='leadacao',
            name='pdf_omie',
            field=models.FileField(blank=True, null=True, upload_to='leads_omie/'),
        ),
        migrations.AlterField(
            model_name='leadacao',
            name='acao',
            field=models.CharField(choices=[(0, 'Criação'), (1, 'Comentarios'), (2, 'Alteração de Status'), (3, 'Solicitação de Cliente'), (4, 'Informação de Analise'), (5, 'Troca de Responsável'), (6, 'Informação para o comprador'), (7, 'Produto adicionado ao lead'), (8, 'Produto removido do lead'), (9, 'Produto editado'), (10, 'Lead agurdando Retorno'), (11, 'Informação para vendas')], max_length=20),
        ),
    ]
