# Generated by Django 5.1.7 on 2025-03-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0024_alter_lead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'permissions': [('pode_ver_fluxo', 'Pode visualizar o fluxo de Leads'), ('pode_modificar_analise', 'Pode modificar Leads no status Análise'), ('pode_modificar_atendimento', 'Pode modificar Leads no status Atendimento'), ('pode_modificar_apc', 'Pode modificar Leads no status APC'), ('pode_modificar_apv', 'Pode modificar Leads no status APV'), ('pode_modificar_orcamento', 'Pode modificar Leads no status Orçamento'), ('pode_modificar_followup', 'Pode modificar Leads no status Follow-up'), ('pode_ver_todos_leads', 'Pode ver todos os Leads'), ('pode_declinar_lead', 'Pode declinar Leads'), ('pode_excluir_lead', 'Pode excluir Leads')]},
        ),
    ]
