# Generated by Django 5.1.7 on 2025-03-10 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0025_alter_lead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'permissions': [('gerencia_usuario', 'Gerencia Usuário')]},
        ),
    ]
