# Generated by Django 5.1.7 on 2025-03-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0027_perfilusuario_cep_fim_perfilusuario_cep_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_vendedor',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
