# Generated by Django 5.1.7 on 2025-03-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0029_alter_perfilusuario_cep_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='cep_fim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cep_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='codigo_vendedor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
