# Generated by Django 5.1.7 on 2025-03-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0030_alter_perfilusuario_cep_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_vendedor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
