# Generated by Django 5.1.7 on 2025-03-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0033_leadassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='vendedor_mot',
            field=models.IntegerField(choices=[(0, 'Sem Criterios'), (1, 'Vendedor responsável no Omie'), (2, 'Vendedor com faixa de CEP'), (3, 'Vendedor com histórico de atribuições')], default=0),
        ),
    ]
