# Generated by Django 5.1.7 on 2025-03-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0034_lead_vendedor_mot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(max_length=255),
        ),
    ]
