# Generated by Django 5.1.7 on 2025-03-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0035_alter_cliente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
